### ISSUE TITLE
No win32 support?

### ISSUE THREAD

**Issue by ivanooi** [maketechnology/chromium.swt#36]
Hi, 

  I try to install it in Eclipse win32 but it failed. There;s no problem for Mac OS X.

Thanks

**Comment by gzunino** [comment]
Windows, Linux and Mac OSX are supported in 64bit version only.

Please add more details of you environment, stdout logs, target platform, etc if is not working on any of these environments.

**Comment by ivanooi** [comment]
JDK1.8 Eclipse 2018-09, I'm still stick with 32bit as my app are build for volunteer... and some of them still using WinXP.... Thanks

**Comment by jcompagner** [comment]
i guess this one can be closed, there should not be any 32 bit investment into this plugin
Because also Eclipse kind of removed all 32 bit builds for all systems starting with the latest release.

We need good 64 bit builds, also under Linux because they also dropped gtk2 support (so this plugin should support 64 bit and gtk3)

**Comment by gzunino** [comment]
@ivanooi I'm closing this as 32 bit is not in the scope of this project. If you are interested we may offer this separately, please contact me at guillez at gmail dot com
