### ISSUE TITLE
Menu handler not working

### ISSUE THREAD

**Issue by dstainhauser** [maketechnology/chromium.swt#59]
Thanks for the fix. But we still do not get a custom menu in the browser. 

For example, like this:

```
@Override
public void createPartControl(Composite parent) {
        Composite composite = new Composite(parent, SWT.NONE);
	FillLayout layout = new FillLayout();
	composite.setLayout(layout);
	browser = new Browser(composite, SWT.NONE);
	browser.setText(htmlText);
	menu = new Menu(browser);
	addMenuItems(menu);
	menu.setVisible(false);
	browser.setMenu(menu);
 }
```

Right click in a chromium web page brings the standard chrome menu

<img width="174" alt="image" src="https://user-images.githubusercontent.com/1434584/56759258-d8b5e500-6798-11e9-8942-1a9c3eb79f04.png">

_Originally posted by @dstainhauser in https://github.com/maketechnology/chromium.swt/issues/49#issuecomment-486787450_

**Comment by gzunino** [comment]
I tested the same code in linux, windows and mac and I'm getting the menu correctly. Take a look:
![VirtualBox_Capitan_25_04_2019_21_07_06](https://user-images.githubusercontent.com/2495175/56775811-2f262200-679f-11e9-84b5-a55e5ac7c1f0.png)

I think there could be something wrong with the p2 repo published because I'm getting other bug reports that work fine here. I'll double check

**Comment by dstainhauser** [comment]
Hi Guillermo

Thanks for implementing the menu handler and checking yesterday. This was my fault. The menu is now working perfectly. I missed it due to another problem, which was related with the menu. Actually, the mouse events are not propagated. We added the menu after a mouse down event, but since those events are not propagated, we also had no menu. I will report it in a new issue.
