### ISSUE TITLE
console.log is slowing down the browser significantly

### ISSUE THREAD

**Issue by MichaelFroeschen** [maketechnology/chromium.swt#66]
This is just a minor issue since console.log should be avoided, but because a lib produced log entries i noticed, that it slows down the execution of js code significantly.

An example is available at: https://github.com/MichaelFroeschen/chromium-swt-spc-poc

Just run the application, click Views, click 'Open Issue 66 Example'
It might take a while, but after some time you will see how long it took for 20.000 iterations that only contain a console.log call

**Comment by dstainhauser** [comment]
We observe the same problem. Are using Chromium as an EPUB Reader and therefore chromium dumps huge amounts of data to the console, which slows down the execution of the app in a drastic way. 

Could you please compile and publish a version without debug log, so it can be used for production use? Thanks a lot

**Comment by jcompagner** [comment]
the problem is for the most part in these 2 methods of the Chromium class

    private jnr.ffi.Pointer debugPrint(String log) {
//        System.out.println("J"+instance + ":" + Thread.currentThread().getName() +":" + log + (this.url != null ? " (" + getPlainUrl(this.url) + ")" : " empty-url"));
        return null;
    }
    
    private static jnr.ffi.Pointer debug(String log) {
//        System.out.println("J:" + log);
        return null;
    }

if i comment those out then most of the logging is gone.

Normally in eclipse i guess we use the Plugins.getLog() thing, but that Chromium doesn't have a Activator/IPlugin at all as far as i know.

All other logging are all done in the ".rs" files like:
 println!("<<<<<<<< set_focus {}", focus);
and
  println!("Calling cef_browser_host_create_browser");

Maybe for the Chromium class we could have:

class Chromium extends WebBrowser {
	private static final boolean debug = Boolean.valueOf(System.getProperty("swt.chromium.debug", "false"));

and then

    private jnr.ffi.Pointer debugPrint(String log) {
    	if (debug) System.out.println("J"+instance + ":" + Thread.currentThread().getName() +":" + log + (this.url != null ? " (" + getPlainUrl(this.url) + ")" : " empty-url"));
        return null;
    }
    
    private static jnr.ffi.Pointer debug(String log) {
    	if (debug) System.out.println("J:" + log);
        return null;
    }
so that when debugging you just give a system property "swt.chromium.debug" the value "true"
