### ISSUE TITLE
Overriding "parent" field on JNR's Class Loader fails on Java 12

### ISSUE THREAD

**Issue by TimWebb** [maketechnology/chromium.swt#69]
Access to override the `parent` field on `ClassLoader` appears to be restricted in Java 12. Specifically the code that is running in:

`private static void fixJNRClosureClassLoader() in Chromium.java`

If I move the JNR libraries as Jars embedded in `org.eclipse.swt.chromium` and remove this `fixJNRClosureClassLoader` then I correctly see the Chromium browser opening.  Without it, things generally fail as expected including the exception about missing field.

My gut says that we shouldn't be rewiring the parent class loader for a shared Bundle that could be used by other services to work around a class loading issue. Perhaps there is an alternate way to fix this?  Or we may need a change in JNR itself in terms of being more OSGi friendly?

**Comment by TimWebb** [comment]
Not sure if this change is related to the fix we would need:
https://github.com/jnr/jnr-ffi/commit/82f954fcc854fd37138ee037c95f3e213f0acad7#diff-4d6d896dcd6bfb6d31b2464cc56efc00

I'm not familiar with JNR but seems promising.

**Comment by jcompagner** [comment]
yes this is a problem because in java 12 this is not allowed anymore:
https://stackoverflow.com/questions/56039341/get-declared-fields-of-java-lang-reflect-fields-in-jdk12

they (jnr) should have been using the context classloader (so we could set that quickly)
there is a discussion about that:
https://github.com/jnr/jnr-ffi/issues/51

problem they fixed it a bit (but i don't think that will be enough) but that code is not what we are using..
As far as i can see we are still using code before this commit:
https://github.com/jnr/jnr-ffi/commit/82f954fcc854fd37138ee037c95f3e213f0acad7

(if we use the jnr libs that eclipse is providing)

**Comment by jcompagner** [comment]
ok this is another hack but it fixes the problem with the current code:

  private static void fixJNRClosureClassLoader() {
        try {
            ClosureManager closureManager = NativeRuntime.getInstance().getClosureManager();
            Field classLoader = findField(closureManager.getClass(), "classLoader");
            classLoader.setAccessible(true);
            
            Class<?> asmClass = closureManager.getClass().getClassLoader().loadClass("jnr.ffi.provider.jffi.AsmClassLoader");
            Constructor<?> constructor = asmClass.getConstructor(ClassLoader.class);
            constructor.setAccessible(true);
            Object newInstance = constructor.newInstance(Chromium.class.getClassLoader());
            classLoader.set(closureManager,newInstance);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

so instead of setting the parent of the classloader class, that just overrides the complete AsmClassLoader field with a new instance that is correctly made with the right parent..

**Comment by TimWebb** [comment]
Thanks, I did confirm that running with *2.1.9* bundle of `com.github.jnr.ffi` will allow this to work without needing the parent classloader changed.

**Comment by jcompagner** [comment]
problem is a bit that Eclipse (orbit) https://download.eclipse.org/tools/orbit/downloads/drops/R20190226160451/
should be updated then to have the latest libs.
Or all those dependencies should be a in anothe repo that holds those 4a5 jars (excluding asm)

**Comment by gzunino** [comment]
JNR has been removed in 0.10.0. There is no more hacking with classloader
